#define EZI2C_INTR_PRIORITY             (1u)
#define EZI2C_INTR_NUM        CYBSP_I2C_IRQ
#define CAPSENSE_INTR_PRIORITY          (3u)
#define SETUP_INTR_PRIORITY             (2u)
#define CY_ASSERT_FAILED                (0u)


#define I2C_SLAVE_ADDR_START 0x5AU
#define PSOC_TOUCH_STATUS_REG 0x0
#define PSOC_RAW_VALUE_REG_START 0x02
#define PSOC_BASELINE_REG_START 0x1A

#define PSOC_FINGER_THRESHOLD_REG 0x32
#define PSOC_NOISE_THRESHOLD_REG 0x34
#define PSOC_NEG_NOISE_THRESHOLD_REG 0x36   
#define PSOC_LOW_BASELINE_RESET_REG 0x38
#define PSOC_HYSTERESIS_REG 0x39
#define PSOC_ON_DEBOUNCE_REG 0x40
#define PSOC_IDAC_COMP_N_REG 0x41
#define PSOC_IDAC_COMP_VAL_REG 0x42
#define PSOC_READ_CMD_REG 0x4E
#define PSOC_CMD_REG 0x4F 

#define REG_MAP_SIZE 80